apiVersion: v1
kind: Service
metadata:
  namespace: woovi-mongo-dev
  labels:
    name: mongodb1
  name: mongodb1
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongodb1
